resolver: lts-18.18

extra-deps:
  - elm-street-0.1.0.4
  - postgresql-simple-migration-0.1.15.0
  - prometheus-client-1.1.0
  - data-sketches-0.3.1.0       # for prometheus
  - data-sketches-core-0.1.0.0  # for prometheus
  - relude-1.0.0.1

  - github: kowainik/cake-slayer
    commit: 20e0b0cf3277a6f63354c72758630fd3a22fef5c

  - github: holmusk/postgresql-simple-named
    commit: 394e6ff593666616f78f59a7b4817608a2950370